### ISSUE TITLE
Continuously crashes right after commissioning

### ISSUE THREAD

**Issue by bakerface** [FirstBuild/chillhub-firmware#14]
If Firebase shows the following at boot, then the firmware will crash:

```
- devices
  - chillhubs
    - 0ec48540-d259-11e4-9a59-afb430376952
      - status: "disconnected"
```

Here is the error:

```
> chillhub-firmware@0.1.12 start /src
> node chillhub.js

Package file opened.
Found software version: 0.1.12
Sending this SW version to firebase: 0.1.12
Config file opened.
Successful firebase login.
FIREBASE WARNING: Exception was thrown by user callback. Error: Firebase.update failed: First argument contains undefined in property 'created'
    at Error (<anonymous>)
    at Pb (/src/node_modules/firebase/lib/firebase-node.js:30:58)
    at /src/node_modules/firebase/lib/firebase-node.js:31:252
    at ua (/src/node_modules/firebase/lib/firebase-node.js:8:620)
    at Pb (/src/node_modules/firebase/lib/firebase-node.js:31:9)
    at Ob (/src/node_modules/firebase/lib/firebase-node.js:29:428)
    at Rb (/src/node_modules/firebase/lib/firebase-node.js:32:243)
    at Q.R.update (/src/node_modules/firebase/lib/firebase-node.js:230:369)
    at register (/src/lib/chillhub.js:97:23)
    at gotRoot (/src/lib/chillhub.js:159:17) 

/src/node_modules/firebase/lib/firebase-node.js:24
ion(){z("Exception was thrown by user callback.",b.stack||"");throw b;},Math.f
                                                                    ^
Error: Firebase.update failed: First argument contains undefined in property 'created'
    at Error (<anonymous>)
    at Pb (/src/node_modules/firebase/lib/firebase-node.js:30:58)
    at /src/node_modules/firebase/lib/firebase-node.js:31:252
    at ua (/src/node_modules/firebase/lib/firebase-node.js:8:620)
    at Pb (/src/node_modules/firebase/lib/firebase-node.js:31:9)
    at Ob (/src/node_modules/firebase/lib/firebase-node.js:29:428)
    at Rb (/src/node_modules/firebase/lib/firebase-node.js:32:243)
    at Q.R.update (/src/node_modules/firebase/lib/firebase-node.js:230:369)
    at register (/src/lib/chillhub.js:97:23)
    at gotRoot (/src/lib/chillhub.js:159:17)

npm ERR! chillhub-firmware@0.1.12 start: `node chillhub.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the chillhub-firmware@0.1.12 start script.
npm ERR! This is most likely a problem with the chillhub-firmware package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node chillhub.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls chillhub-firmware
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.18.9-3-ARCH
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /src
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /src/npm-debug.log
npm ERR! not ok code 0
```

**Comment by bakerface** [comment]
I have found a way to fix the issue. If you delete all of the data for that user in firebase, then the firmware will recover automatically.
